---
name: "Java CI"

on:
  push:
    branches:
      - "master"
    tags:
      - "**"
  pull_request:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  build:
    runs-on: "debian-latest"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-java@v3"
        with:
          java-version: "21"
          distribution: "openjdk"

      - uses: "gradle/gradle-build-action@v2"
        arguments: "build"
        build-root-directory: "app"

      - name: "Publish code coverage"
        uses: "paambaati/codeclimate-action@v5.0.0"
        env:
          - "CC_TEST_REPORTER_ID=${{secrets.CC_TEST_REPORTER_ID}}"
          - "JACOCO_SOURCE_PATH=${{github.workspace}}/app/src/main/java"
        with:
          workingDirectory: "${{github.workspace}}/app"
          coverageCommand: "./gradlew jacocoTestReport"
          coverageLocations: "${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco"
...
